-- Added by ipokesnails
-- Code generated by ChatGPT

FavoriteLists = {}

local FAVORITES_DIR = "Favorites"

-- Cache[player] = {
--     [listName] = {
--         [songDir] = true
--     }
-- }
FavoriteLists.Cache = {}

local function GetProfileDir(pn)
    if pn == PLAYER_1 then
        return PROFILEMAN:GetProfileDir(0)
    elseif pn == PLAYER_2 then
        return PROFILEMAN:GetProfileDir(1)
    end
    return nil
end

local function GetFavoritesDir(pn)
    local profileDir = GetProfileDir(pn)
    if not profileDir or profileDir == "" then
        return nil
    end
    return profileDir .. FAVORITES_DIR .. "/"
end

local function GetListFile(pn, listName)
    local favoritesDir = GetFavoritesDir(pn)
    if not favoritesDir then
        return nil
    end
    return favoritesDir .. listName .. ".txt"
end

local function ReadList(path)
    local file = RageFileUtil:CreateRageFile()

    -- Temporary diagnostic start
        Trace("[FavoriteLists] CreateRageFile returned: " .. tostring(file))

    if not file then
        Trace("[FavoriteLists] ERROR: CreateRageFile returned nil for " .. path)
        return {}
    end
    -- temporary diagnostic end
    
    if not file:Open(path, 1) then
        file:destroy()
        return {}
    end

    local songs = {}

    while not file:AtEOF() do
        local songDir = file:GetLine()
        if songDir and songDir ~= "" then
            songs[songDir] = true
        end
    end

    file:Close()
    file:destroy()

    return songs
end

local function WriteList(path, songs)
    local file = RageFileUtil:CreateRageFile()

    if not file:Open(path, 2) then
        Trace("[FavoriteLists] Error writing to " .. path .. ": " .. file:GetError())
        file:destroy()
        return false
    end

    for songDir, _ in pairs(songs) do
        file:PutLine(songDir)
    end

    file:Close()
    file:destroy()

    return true
end

function FavoriteLists.GetProfileDir(pn)
    return GetProfileDir(pn)
end

function FavoriteLists.GetLists(pn)
    local favoritesDir = GetFavoritesDir(pn)

    if not favoritesDir then
        return {}
    end

    local files = FILEMAN:GetDirListing(favoritesDir, false, true)
    local lists = {}

    for _, filename in ipairs(files) do
        if filename:match("%.txt$") then
            local listName = filename:match("([^/]+)%.txt$")

            if listName then
                table.insert(lists, listName)
            end
        end
    end

    table.sort(lists)

    return lists
end

-- Reload all favorite files for a player into memory.
function FavoriteLists.Refresh(pn)
    local cache = {}

    for _, listName in ipairs(FavoriteLists.GetLists(pn)) do
        local path = GetListFile(pn, listName)

        if path then
            cache[listName] = ReadList(path)
        end
    end

    FavoriteLists.Cache[pn] = cache
end

function FavoriteLists.Contains(pn, listName, song)
    if not song then
        return false
    end

    -- Make sure the cache exists.
    if not FavoriteLists.Cache[pn] then
        FavoriteLists.Refresh(pn)
    end

    local list = FavoriteLists.Cache[pn][listName]

    if not list then
        return false
    end

    return list[song:GetSongDir()] == true
end

function FavoriteLists.Add(pn, listName, song)
    local path = GetListFile(pn, listName)

    if not path or not song then
        return false
    end

    if not FavoriteLists.Cache[pn] then
        FavoriteLists.Refresh(pn)
    end

    local songs = FavoriteLists.Cache[pn][listName]

    if not songs then
        songs = {}
        FavoriteLists.Cache[pn][listName] = songs
    end

    songs[song:GetSongDir()] = true

    return WriteList(path, songs)
end

function FavoriteLists.Remove(pn, listName, song)
    local path = GetListFile(pn, listName)

    if not path or not song then
        return false
    end

    if not FavoriteLists.Cache[pn] then
        FavoriteLists.Refresh(pn)
    end

    local songs = FavoriteLists.Cache[pn][listName]

    if not songs then
        return false
    end

    songs[song:GetSongDir()] = nil

    return WriteList(path, songs)
end

function FavoriteLists.Toggle(pn, listName, song)
    if FavoriteLists.Contains(pn, listName, song) then
        return FavoriteLists.Remove(pn, listName, song)
    else
        return FavoriteLists.Add(pn, listName, song)
    end
end

-- Return all favorite lists and their songs for use by C++.
function FavoriteLists.GetWheelData(pn)
    if not FavoriteLists.Cache[pn] then
        FavoriteLists.Refresh(pn)
    end

    return FavoriteLists.Cache[pn] or {}
end
